{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-ktx",
    "version": "7.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-7.3.1.aar",
          "url": "databinding-ktx-7.3.1.aar",
          "size": 11657,
          "sha512": "bd8c92b1340d68bfe9073a259e900c92301f80a3ae76f36e3b11812aae9821a1f3d14d08403b82f32fdef71a3b0b3a262b5ef1ac72403dff9123cbcf544584a9",
          "sha256": "8db330b55e07a43bd84c3e722505c5379449baf5ef3ab7f5e1280bb8593c8162",
          "sha1": "eae305670dfc80900259ff5c38c75c2b69b95244",
          "md5": "f269074492f90b29ce9d5ecfb3f9ad72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-ktx-7.3.1.aar",
          "url": "databinding-ktx-7.3.1.aar",
          "size": 11657,
          "sha512": "bd8c92b1340d68bfe9073a259e900c92301f80a3ae76f36e3b11812aae9821a1f3d14d08403b82f32fdef71a3b0b3a262b5ef1ac72403dff9123cbcf544584a9",
          "sha256": "8db330b55e07a43bd84c3e722505c5379449baf5ef3ab7f5e1280bb8593c8162",
          "sha1": "eae305670dfc80900259ff5c38c75c2b69b95244",
          "md5": "f269074492f90b29ce9d5ecfb3f9ad72"
        }
      ]
    }
  ]
}
